-- init-permissions.sql
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'rootpass' WITH GRANT OPTION;
GRANT REPLICATION SLAVE ON *.* TO 'repli_user'@'%' IDENTIFIED BY 'replipass';
GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'sst_user'@'%' IDENTIFIED BY 'sstpass';
GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'sst_user'@'localhost' IDENTIFIED BY 'sstpass';
CREATE USER IF NOT EXISTS 'haproxy_check'@'10.6.0.100';
GRANT USAGE ON *.* TO 'haproxy_check'@'10.6.0.100';
FLUSH PRIVILEGES;
