-- init-permissions.sql
CREATE USER IF NOT EXISTS 'root'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'repli_user'@'%' IDENTIFIED BY 'replipass';
GRANT REPLICATION SLAVE ON *.* TO 'repli_user'@'%';
CREATE USER IF NOT EXISTS 'sst_user'@'%' IDENTIFIED BY 'sstpass';
GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'sst_user'@'%';
CREATE USER IF NOT EXISTS 'sst_user'@'localhost' IDENTIFIED BY 'sstpass';
GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'sst_user'@'localhost';
CREATE USER IF NOT EXISTS 'haproxy_check'@'10.6.0.100';
GRANT USAGE ON *.* TO 'haproxy_check'@'10.6.0.100';
FLUSH PRIVILEGES;
