#!/bin/bash

# Configuration
MASTER_IP="10.5.0.11"
MASTER_PORT=3411
SLAVE1_PORT=3412
SLAVE2_PORT=3413
USER="root"
PASS="rootpass"
REPLI_USER="repli_user"
REPLI_PASS="replipass"

echo "=========================================================="
echo "⚙️  MariaDB Replication Setup (using mariadb-dump)"
echo "=========================================================="

# Function to execute SQL on host ports
run_sql() {
    local port=$1
    local query=$2
    mariadb -h 127.0.0.1 -P $port -u$USER -p$PASS -sN -e "$query" 2>/dev/null
}

echo "1. ⏳ Waiting for Master and Slaves to be ready (max 90s)..."
MAX_WAIT=90
START_WAIT=$(date +%s)
READY=false

while [ $(($(date +%s) - START_WAIT)) -lt $MAX_WAIT ]; do
    ALL_UP=true
    # Check Master and both Slaves connectivity
    for port in $MASTER_PORT $SLAVE1_PORT $SLAVE2_PORT; do
        if ! run_sql $port "SELECT 1" > /dev/null 2>&1; then
            ALL_UP=false
            break
        fi
    done
    
    if $ALL_UP; then
        READY=true
        break
    fi
    echo -n "."
    sleep 2
done
echo ""

if [ "$READY" = false ]; then
    echo "❌ Timeout: Master or Slaves not reachable after 90s."
    exit 1
fi

echo "✅ All nodes are reachable. Proceeding with setup..."

for port in $SLAVE1_PORT $SLAVE2_PORT; do
    echo -e "\n2. ⛓️  Initializing Slave on Port $port..."
    
    echo ">> Resetting Slave..."
    run_sql $port "STOP SLAVE;"
    run_sql $port "RESET SLAVE ALL;"
    
    echo ">> Dumping data from Master and piping to Slave (with --master-data=1)..."
    # We use sed to inject MASTER_HOST, MASTER_USER and MASTER_PASSWORD into the CHANGE MASTER TO command
    # generated by --master-data=1.
    mariadb-dump -h 127.0.0.1 -P $MASTER_PORT -u$USER -p$PASS \
        --all-databases \
        --master-data=1 \
        --single-transaction \
        --routines --triggers --events \
        | sed "0,/^CHANGE MASTER TO /s/^CHANGE MASTER TO /CHANGE MASTER TO MASTER_HOST='$MASTER_IP', MASTER_USER='$REPLI_USER', MASTER_PASSWORD='$REPLI_PASS', /" \
        | mariadb -h 127.0.0.1 -P $port -u$USER -p$PASS

    if [ $? -eq 0 ]; then
        echo "✅ Data sync and Master link successful for Port $port."
    else
        echo "❌ Failed to sync data or link Master for Port $port."
        continue
    fi
    
    echo ">> Starting Slave and enforcing configuration (Read-Only, GTID)..."
    run_sql $port "START SLAVE; SET GLOBAL read_only=ON; SET GLOBAL gtid_strict_mode=ON;"
    
    echo ">> Checking Slave Status..."
    # Wait a bit for the IO thread to connect
    sleep 2
    STATUS=$(mariadb -h 127.0.0.1 -P $port -u$USER -p$PASS -e "SHOW SLAVE STATUS\G")
    IO_RUNNING=$(echo "$STATUS" | grep "Slave_IO_Running:" | awk '{print $2}')
    SQL_RUNNING=$(echo "$STATUS" | grep "Slave_SQL_Running:" | awk '{print $2}')
    GTID_MODE=$(run_sql $port "SELECT @@gtid_strict_mode;")
    READ_ONLY=$(run_sql $port "SELECT @@read_only;")
    
    if [ "$IO_RUNNING" == "Yes" ] && [ "$SQL_RUNNING" == "Yes" ]; then
        echo "✅ Slave on Port $port is UP and RUNNING (GTID: $GTID_MODE, RO: $READ_ONLY)"
    else
        echo "❌ Slave on Port $port has issues (IO: $IO_RUNNING, SQL: $SQL_RUNNING)"
        echo "$STATUS" | grep -E "Last_IO_Error|Last_SQL_Error"
    fi
done

echo -e "\n=========================================================="
echo "🏁 Replication Setup Finished"
echo "=========================================================="
